language: java

notifications:
  email: false

before_install:
  - chmod +x prepare-build.sh
  - ./prepare-build.sh

script:
  - mvn package
  - mvn checkstyle:check

after_success:
  - mvn clean cobertura:cobertura coveralls:report 
